myapps/todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.home_page, name='index'),
    path('about/', views.about_page, name='about'),
    path('complete/<int:todo_id>/', views.complete_todo, name='complete'),
    path('delete/<int:todo_id>/', views.delete_todo, name='delete'),
    path('delete-completed/', views.delete_completed, name='delete-completed'),
    path('delete/', views.delete_all, name='delete-all'),
]

todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapps.todos.urls')),
]

myapps/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=254)
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

myapps/todos/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ('title',)
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insert Todo...(min 5 characters)',
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = ''

myapps/todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Todo
from .forms import TodoForm


# Create your views here.
def home_page(request):
    form = TodoForm(request.POST or None)
    todos = Todo.objects.all()

    if request.method == 'POST':
        if form.is_valid():
            if len(form.cleaned_data['title']) > 4:
                form.save()
            return redirect('todos:index')

    return render(request, 'todos/index.html', {
        'todos': todos,
        'form': form,
    })


def about_page(request):
    return render(request, 'todos/about.html', {})


def complete_todo(request, todo_id):
    todo = get_object_or_404(Todo, id=todo_id)
    todo.is_completed = True
    todo.save()
    return redirect('todos:index')


def delete_todo(request, todo_id):
    todo = get_object_or_404(Todo, id=todo_id)
    todo.delete()
    return redirect('todos:index')


def delete_completed(request):
    todos_completed = Todo.objects.filter(is_completed=True).delete()
    return redirect('todos:index')


def delete_all(request):
    todos = Todo.objects.all().delete()
    return redirect('todos:index')

myapps/todos/templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="description" content="Application by Aniket Aryamane">
	<meta name="author" content="Aniket Aryamane">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>{% block title %}{% endblock %}</title>
	<link rel="apple-touch-icon" href="">

	{% load static %}

	<!-- Link to Bootstrap CSS file -->
	<link rel="stylesheet" href="{% static 'todos/css/vendor/bootstrap/bootstrap.min.css' %}" type="text/css">

	<!-- Link to Materialize CSS file -->
	<!-- <link rel="stylesheet" href="{% static 'todos/css/vendor/materialize/materialize.min.css' %}" type="text/css"> -->

	<!-- Link to Font-Awesome CSS file -->
	<link rel="stylesheet" href="{% static 'todos/css/vendor/font-awesome/css/all.css' %}" type="text/css">

	<!-- Link to your favicon.ico file -->
	<link rel="shortcut icon" href="{% static 'todos/img/favicon.ico' %}" type="image/x-icon">

	<!-- Link to your css file -->
	<link rel="stylesheet" href="{% static 'todos/css/main.css' %}" type="text/css">

</head>

<body>
	{% include '_navbar.html' %}
	{% block content %}{% endblock %}


	<!-- Link to Materialize JS file -->
	<!-- <script src="{% static 'todos/js/vendor/materialize/materialize.min.js' %}"></script> -->

	<!-- JQuery comes first in the list -->
	<script src="{% static 'todos/js/vendor/bootstrap/jquery-3.4.1.min.js' %}"></script>
	<script src="{% static 'todos/js/vendor/bootstrap/popper.min.js' %}"></script>
	<script src="{% static 'todos/js/vendor/bootstrap/bootstrap.min.js' %}"></script>

	<!-- Link to your js file -->
	<script src="{% static 'todos/js/main.js' %}"></script>

	<!-- Link to your extra javascript/jquery file -->
	{% block extra_js %}{% endblock %}
</body>

</html>

myapps/todos/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
    <a class="navbar-brand" href="{% url 'todos:index' %}">Todo App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        {% with url_name=request.resolver_match.url_name %}
          <a href="{% url 'todos:index' %}" class="nav-item nav-link {% if url_name == 'index' %}active{% endif %}">Todos</a>
          <a href="{% url 'todos:about' %}" class="nav-item nav-link {% if url_name == 'about' %}active{% endif %}">About</a>
        {% endwith %}
      </div>
    </div>
  </div>
</nav>

myapps/todos/templates/todos/about.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
  Todos | About
{% endblock %}

{% block content %}
  <div class="container">
    <h2>About Us</h2>
    <h6 class="mt-3">Copyright &#9400; 2019 - Aniket Aryamane</h6>
  </div>
{% endblock %}

myapps/todos/templates/todos/index.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
  Todos | Home
{% endblock %}

{% block content %}
  <div class="container">
    <form method="POST">
      {% csrf_token %}
      <div class="input-group mb-3">
        {{ form }}
        <div class="input-group-append">
          <button class="btn btn-sm btn-primary" type="submit">Create ToDo</button>
        </div>
      </div>
      <div class="mb-3">
        <a href="{% url 'todos:delete-completed' %}" class="btn btn-sm btn-danger mr-1">Delete Completed</a>
        <a href="{% url 'todos:delete-all' %}" class="btn btn-sm btn-danger">Delete All</a>
      </div>
    </form>
    <ul class="list-group">
      {% for todo in todos %}
        <li class="list-group-item d-flex align-items-center justify-content-between">
          {% if todo.is_completed %}
            <strike>
              {{ todo }}
            </strike>
          {% else %}
            {{ todo }}
          {% endif %}
          <div>
            {% if todo.is_completed %}
              <a href="{% url 'todos:complete' todo_id=todo.id %}" class="btn btn-sm btn-info mr-2 disabled">Complete</a>
            {% else %}
              <a href="{% url 'todos:complete' todo_id=todo.id %}" class="btn btn-sm btn-info mr-2">Complete</a>
            {% endif %}
            <a href="{% url 'todos:delete' todo_id=todo.id %}" class="btn btn-sm btn-danger">Delete</a>
          </div>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}